/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/extract.json
export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type CallEditorialGuidelines = {
  _id: string;
  _type: "callEditorialGuidelines";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  introLead: string;
  introSupportingText: string;
  submissionLabel: string;
  submissionEmail: string;
  submissionNote: string;
  researchFields: Array<string>;
  acceptedLanguages: Array<string>;
  contributionTypes: Array<{
    title: string;
    content: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: "bullet";
      markDefs?: null;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    _type: "contributionType";
    _key: string;
  }>;
  editorialRules: Array<{
    text: string;
    _type: "editorialRule";
    _key: string;
  }>;
  footnoteExamples: Array<{
    editorLabel: string;
    content: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: null;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    _type: "editorialExample";
    _key: string;
  }>;
  bibliographyIntro: string;
  bibliographyExamples: Array<{
    editorLabel: string;
    content: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: null;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    _type: "editorialExample";
    _key: string;
  }>;
  englishDescription: string;
  englishPdf: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  englishLinkLabel: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  introText: string;
  aboutUsText: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  navigationCategories: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  licenseText: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  contactEmail?: string;
  facebookUrl?: string;
  instagramUrl?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  bio?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  subtitle?: string;
  authors: Array<
    {
      _key: string;
    } & AuthorReference
  >;
  category: CategoryReference;
  publishedAt: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  thumbnailImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  excerpt?: string;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<
          | {
              href?: string;
              _type: "link";
              _key: string;
            }
          | {
              text: string;
              _type: "footnote";
              _key: string;
            }
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
  >;
  pdf?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityFileAssetReference
  | CallEditorialGuidelines
  | SanityImageAssetReference
  | CategoryReference
  | SiteSettings
  | SanityImageCrop
  | SanityImageHotspot
  | Author
  | Slug
  | AuthorReference
  | CategoryReference
  | Post
  | Category
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/queries/authors.ts
// Variable: AUTHOR_QUERY
// Query: {  "author": *[_type == "author" && slug.current == $slug][0] {    _id,    name,    bio,    image {      ...,      alt    },    slug  },  "posts": *[    _type == "post" &&    references(*[_type == "author" && slug.current == $slug]._id)  ] | order(publishedAt desc) {    _id,    title,    slug,    publishedAt,    excerpt,    subtitle,    thumbnailImage {      ...,      alt    },    image {      ...,      alt    },    authors[]-> {      _id,      name,      slug    },    category-> {      _id,      title,      slug    }  }}
export type AUTHOR_QUERY_RESULT = {
  author: {
    _id: string;
    name: string;
    bio: string | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string | null;
      _type: "image";
    } | null;
    slug: Slug;
  } | null;
  posts: Array<{
    _id: string;
    title: string;
    slug: Slug;
    publishedAt: string;
    excerpt: string | null;
    subtitle: string | null;
    thumbnailImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string | null;
      _type: "image";
    } | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      alt: null;
    } | null;
    authors: Array<{
      _id: string;
      name: string;
      slug: Slug;
    }>;
    category: {
      _id: string;
      title: string;
      slug: Slug;
    };
  }>;
};

// Source: src/sanity/queries/callEditorialGuidelines.ts
// Variable: CALL_EDITORIAL_GUIDELINES_QUERY
// Query: *[		_type == "callEditorialGuidelines" &&		_id == "callEditorialGuidelines"	][0] {		_id,		introLead,		introSupportingText,		submissionLabel,		submissionEmail,		submissionNote,		researchFields,		acceptedLanguages,		contributionTypes[] {			_key,			title,			content		},		editorialRules[] {			_key,			text		},		footnoteExamples[] {			_key,			content		},		bibliographyIntro,		bibliographyExamples[] {			_key,			content		},		englishDescription,		"englishPdfUrl": englishPdf.asset->url,		englishLinkLabel	}
export type CALL_EDITORIAL_GUIDELINES_QUERY_RESULT = {
  _id: "callEditorialGuidelines";
  introLead: string;
  introSupportingText: string;
  submissionLabel: string;
  submissionEmail: string;
  submissionNote: string;
  researchFields: Array<string>;
  acceptedLanguages: Array<string>;
  contributionTypes: Array<{
    _key: string;
    title: string;
    content: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: "bullet";
      markDefs?: null;
      level?: number;
      _type: "block";
      _key: string;
    }>;
  }>;
  editorialRules: Array<{
    _key: string;
    text: string;
  }>;
  footnoteExamples: Array<{
    _key: string;
    content: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: null;
      level?: number;
      _type: "block";
      _key: string;
    }>;
  }>;
  bibliographyIntro: string;
  bibliographyExamples: Array<{
    _key: string;
    content: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: null;
      level?: number;
      _type: "block";
      _key: string;
    }>;
  }>;
  englishDescription: string;
  englishPdfUrl: string | null;
  englishLinkLabel: string;
} | null;

// Source: src/sanity/queries/categories.ts
// Variable: CATEGORIES_LIST_QUERY
// Query: *[_type == "category"] | order(title asc) {    _id,    title,    slug  }
export type CATEGORIES_LIST_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: Slug;
}>;

// Source: src/sanity/queries/categories.ts
// Variable: CATEGORY_BY_SLUG_QUERY
// Query: *[_type == "category" && slug.current == $slug][0] {		_id,		title,		slug	}
export type CATEGORY_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: Slug;
} | null;

// Source: src/sanity/queries/posts.ts
// Variable: POSTS_QUERY
// Query: *[    _type == "post" &&    defined(slug.current)  ]  | order(publishedAt desc)[0...12]{    _id,    title,    slug,    publishedAt,    authors[]-> {      _id,      name,      slug,	  },  }
export type POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: Slug;
  publishedAt: string;
  authors: Array<{
    _id: string;
    name: string;
    slug: Slug;
  }>;
}>;

// Source: src/sanity/queries/posts.ts
// Variable: POST_BY_SLUG_QUERY
// Query: *[_type == "post" && slug.current == $slug][0]{  _id,  title,  slug,  subtitle,  publishedAt,  body,	image {      ...,      alt    },   authors[]-> {      _id,      name,      slug,	  },}
export type POST_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: Slug;
  subtitle: string | null;
  publishedAt: string;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<
          | {
              text: string;
              _type: "footnote";
              _key: string;
            }
          | {
              href?: string;
              _type: "link";
              _key: string;
            }
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
  >;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    alt: null;
  } | null;
  authors: Array<{
    _id: string;
    name: string;
    slug: Slug;
  }>;
} | null;

// Source: src/sanity/queries/posts.ts
// Variable: POST_BY_CATEGORY_AND_SLUG_QUERY
// Query: *[    _type == "post" &&    slug.current == $slug &&    category->slug.current == $category  ][0]{    _id,    title,    slug,    subtitle,    publishedAt,    body,    image {      ...,      alt    },    "pdfUrl": pdf.asset->url,     authors[]-> {      _id,      name,      slug,	  },    category->{_id, title, slug}  }
export type POST_BY_CATEGORY_AND_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: Slug;
  subtitle: string | null;
  publishedAt: string;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<
          | {
              text: string;
              _type: "footnote";
              _key: string;
            }
          | {
              href?: string;
              _type: "link";
              _key: string;
            }
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
  >;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    alt: null;
  } | null;
  pdfUrl: string | null;
  authors: Array<{
    _id: string;
    name: string;
    slug: Slug;
  }>;
  category: {
    _id: string;
    title: string;
    slug: Slug;
  };
} | null;

// Source: src/sanity/queries/posts.ts
// Variable: POSTS_BY_CATEGORY_QUERY
// Query: *[		_type == "post" &&		category->slug.current == $category	]	| order(publishedAt desc) {		_id,		title,		slug,		publishedAt,    excerpt,    subtitle,		thumbnailImage {			...,			alt		},		image {			...,			alt		},		authors[]-> {			_id,			name,			slug		},		category-> {			_id,			title,			slug		}	}
export type POSTS_BY_CATEGORY_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: Slug;
  publishedAt: string;
  excerpt: string | null;
  subtitle: string | null;
  thumbnailImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | null;
    _type: "image";
  } | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    alt: null;
  } | null;
  authors: Array<{
    _id: string;
    name: string;
    slug: Slug;
  }>;
  category: {
    _id: string;
    title: string;
    slug: Slug;
  };
}>;

// Source: src/sanity/queries/posts.ts
// Variable: ALL_POSTS_WITH_CATEGORY_QUERY
// Query: *[		_type == "post" &&		defined(slug.current) &&		defined(category->slug.current)	] {		"slug": slug.current,		"category": category->slug.current,		_updatedAt	}
export type ALL_POSTS_WITH_CATEGORY_QUERY_RESULT = Array<{
  slug: string;
  category: string;
  _updatedAt: string;
}>;

// Source: src/sanity/queries/posts.ts
// Variable: LATEST_POSTS_QUERY
// Query: *[		_type == "post" &&		defined(slug.current) &&		defined(category->slug.current)	]	| order(publishedAt desc)[0...3] {		_id,		title,		slug,		publishedAt,		excerpt,		subtitle,		thumbnailImage {			...,			alt		},		image {			...,			alt		},		authors[]-> {			_id,			name,			slug		},		category-> {			_id,			title,			slug		}	}
export type LATEST_POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: Slug;
  publishedAt: string;
  excerpt: string | null;
  subtitle: string | null;
  thumbnailImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | null;
    _type: "image";
  } | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    alt: null;
  } | null;
  authors: Array<{
    _id: string;
    name: string;
    slug: Slug;
  }>;
  category: {
    _id: string;
    title: string;
    slug: Slug;
  };
}>;

// Source: src/sanity/queries/siteSettings.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0] {		title,		introText,		aboutUsText,		logo,		contactEmail,		facebookUrl,		instagramUrl	}
export type SITE_SETTINGS_QUERY_RESULT = {
  title: string;
  introText: string;
  aboutUsText: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h2" | "h3" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  contactEmail: string | null;
  facebookUrl: string | null;
  instagramUrl: string | null;
} | null;

// Source: src/sanity/queries/siteSettings.ts
// Variable: LICENSE_TEXT_QUERY
// Query: *[_type == "siteSettings"][0].licenseText
export type LICENSE_TEXT_QUERY_RESULT = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "blockquote" | "h2" | "h3" | "normal";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}> | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '{\n  "author": *[_type == "author" && slug.current == $slug][0] {\n    _id,\n    name,\n    bio,\n    image {\n      ...,\n      alt\n    },\n    slug\n  },\n\n  "posts": *[\n    _type == "post" &&\n    references(*[_type == "author" && slug.current == $slug]._id)\n  ] | order(publishedAt desc) {\n    _id,\n    title,\n    slug,\n    publishedAt,\n    excerpt,\n    subtitle,\n\n    thumbnailImage {\n      ...,\n      alt\n    },\n\n    image {\n      ...,\n      alt\n    },\n\n    authors[]-> {\n      _id,\n      name,\n      slug\n    },\n\n    category-> {\n      _id,\n      title,\n      slug\n    }\n  }\n}': AUTHOR_QUERY_RESULT;
    '\n\t*[\n\t\t_type == "callEditorialGuidelines" &&\n\t\t_id == "callEditorialGuidelines"\n\t][0] {\n\t\t_id,\n\t\tintroLead,\n\t\tintroSupportingText,\n\t\tsubmissionLabel,\n\t\tsubmissionEmail,\n\t\tsubmissionNote,\n\n\t\tresearchFields,\n\t\tacceptedLanguages,\n\n\t\tcontributionTypes[] {\n\t\t\t_key,\n\t\t\ttitle,\n\t\t\tcontent\n\t\t},\n\n\t\teditorialRules[] {\n\t\t\t_key,\n\t\t\ttext\n\t\t},\n\n\t\tfootnoteExamples[] {\n\t\t\t_key,\n\t\t\tcontent\n\t\t},\n\n\t\tbibliographyIntro,\n\n\t\tbibliographyExamples[] {\n\t\t\t_key,\n\t\t\tcontent\n\t\t},\n\n\t\tenglishDescription,\n\t\t"englishPdfUrl": englishPdf.asset->url,\n\t\tenglishLinkLabel\n\t}\n': CALL_EDITORIAL_GUIDELINES_QUERY_RESULT;
    '\n  *[_type == "category"] | order(title asc) {\n    _id,\n    title,\n    slug\n  }\n': CATEGORIES_LIST_QUERY_RESULT;
    '\n\t*[_type == "category" && slug.current == $slug][0] {\n\t\t_id,\n\t\ttitle,\n\t\tslug\n\t}\n': CATEGORY_BY_SLUG_QUERY_RESULT;
    '\n  *[\n    _type == "post" &&\n    defined(slug.current)\n  ]\n  | order(publishedAt desc)[0...12]{\n    _id,\n    title,\n    slug,\n    publishedAt,\n    authors[]-> {\n      _id,\n      name,\n      slug,\n\t  },\n  }\n': POSTS_QUERY_RESULT;
    '*[_type == "post" && slug.current == $slug][0]{\n  _id,\n  title,\n  slug,\n  subtitle,\n  publishedAt,\n  body,\n\timage {\n      ...,\n      alt\n    },\n   authors[]-> {\n      _id,\n      name,\n      slug,\n\t  },\n}': POST_BY_SLUG_QUERY_RESULT;
    '\n  *[\n    _type == "post" &&\n    slug.current == $slug &&\n    category->slug.current == $category\n  ][0]{\n    _id,\n    title,\n    slug,\n    subtitle,\n    publishedAt,\n    body,\n    image {\n      ...,\n      alt\n    },\n    "pdfUrl": pdf.asset->url,\n     authors[]-> {\n      _id,\n      name,\n      slug,\n\t  },\n    category->{_id, title, slug}\n  }\n': POST_BY_CATEGORY_AND_SLUG_QUERY_RESULT;
    '\n\t*[\n\t\t_type == "post" &&\n\t\tcategory->slug.current == $category\n\t]\n\t| order(publishedAt desc) {\n\t\t_id,\n\t\ttitle,\n\t\tslug,\n\t\tpublishedAt,\n    excerpt,\n    subtitle,\n\t\tthumbnailImage {\n\t\t\t...,\n\t\t\talt\n\t\t},\n\t\timage {\n\t\t\t...,\n\t\t\talt\n\t\t},\n\t\tauthors[]-> {\n\t\t\t_id,\n\t\t\tname,\n\t\t\tslug\n\t\t},\n\t\tcategory-> {\n\t\t\t_id,\n\t\t\ttitle,\n\t\t\tslug\n\t\t}\n\t}\n': POSTS_BY_CATEGORY_QUERY_RESULT;
    '\n\t*[\n\t\t_type == "post" &&\n\t\tdefined(slug.current) &&\n\t\tdefined(category->slug.current)\n\t] {\n\t\t"slug": slug.current,\n\t\t"category": category->slug.current,\n\t\t_updatedAt\n\t}\n': ALL_POSTS_WITH_CATEGORY_QUERY_RESULT;
    '\n\t*[\n\t\t_type == "post" &&\n\t\tdefined(slug.current) &&\n\t\tdefined(category->slug.current)\n\t]\n\t| order(publishedAt desc)[0...3] {\n\t\t_id,\n\t\ttitle,\n\t\tslug,\n\t\tpublishedAt,\n\t\texcerpt,\n\t\tsubtitle,\n\t\tthumbnailImage {\n\t\t\t...,\n\t\t\talt\n\t\t},\n\t\timage {\n\t\t\t...,\n\t\t\talt\n\t\t},\n\t\tauthors[]-> {\n\t\t\t_id,\n\t\t\tname,\n\t\t\tslug\n\t\t},\n\t\tcategory-> {\n\t\t\t_id,\n\t\t\ttitle,\n\t\t\tslug\n\t\t}\n\t}\n': LATEST_POSTS_QUERY_RESULT;
    '\n\t*[_type == "siteSettings"][0] {\n\t\ttitle,\n\t\tintroText,\n\t\taboutUsText,\n\t\tlogo,\n\t\tcontactEmail,\n\t\tfacebookUrl,\n\t\tinstagramUrl\n\t}\n': SITE_SETTINGS_QUERY_RESULT;
    '\n\t*[_type == "siteSettings"][0].licenseText\n': LICENSE_TEXT_QUERY_RESULT;
  }
}
